apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-deployment
  labels:
    app: simple-html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-html
  template:
    metadata:
      labels:
        app: simple-html
    spec:
      containers:
        - name: simple-html
          image: your-docker-username/simple-html:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-html-service
spec:
  type: NodePort
  selector:
    app: simple-html
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
